url: "https://vegaalfaro.github.io"
title: "Andrey Alonso Vega, PhD"
theme: minima
author:
  name: Andrey Alonso Vega
  email: vega.andrey@gmail.com

header_pages:
  - index.md
  - blog.md
  - publications.md
  - projects.md


